- includes/RestApiDataAccounting.php
Note: wfGetDB() is deprecated!
> REST API: Add a sample for doing DB modification

- includes/RestApiDataAccounting.php
Tested it and gives expected feedback. Will continue to implement function to provide requested verification hash.
Test Method 'data_input'
curl -X GET http://localhost:9352/rest.php/examples/v1/echo_path_param/ZGF0YV9zZW5kX3dvcmtz/data_input
Test Method 'get_hash'
curl -X GET http://localhost:9352/rest.php/examples/v1/echo_path_param/Z2V0aGFzaHdvcmtzCg==/get_hash
> Rest api rework

- includes/RestApiDataAccounting.php
Resolving two not obvious issues (thanks RHT)
Use MediaWiki\MediaWikiServices;
Use DB_MASTER, not DB_PRIMARY
> RESTAPI: Upgraded codebase to accommodate for issue #8

- extension.json
- includes/RestApiDataAccounting.php
- includes/RestApiDataAccounting_getHash.php
Change path in extension.json to include rev_id in data_input RESTAPI
method.
Fix #24
> Finalise prototype by upgrading RESTAPI data_input with rev_id.

- modules/ext.DataAccounting.signMessage/index.js
todos:
* only sign hash, not whole api response
* fix URI encoding
* store public key not address (probably)
> api calls hooked up initially

- .eslintrc.json
- Example.i18n.alias.php
- extension.json
- external_client/verifier.js
- includes/HashWriterHooks.php
- includes/RestApiDataAccounting.php
- includes/RestApiDataAccounting_getHash.php
- includes/SpecialVerifiedExport.php
- includes/SpecialVerifiedImport.php
- modules/ext.DataAccounting.signMessage/index.js
- package-lock.json
- package.json
- sql/data_accounting.sql
Included the first part of 'The Verifier' which will eventually get into his own repository.
> Special page verified page export

- extension.json
- includes/API/WriteStoreSignedTxHandler.php
- includes/SpecialWitness.php
- includes/SpecialWitnessPublisher.php
- includes/Util.php
Based on https://github.com/ProfessionalWiki/ExternalContent/blob/master/extension.json#L22-L43, https://github.com/ProfessionalWiki/ExternalContent#configuration.
> [REFACTOR] Switch global wg vars to config class

- .github/workflows/ci.yml
- sql/data_accounting.sql
- tests/phpunit/integration/DAApiTest.php
> CI: Add unittest_ to db prefix

- extension.json
- i18n/en.json
- includes/SpecialVerifiedExport.php
- phpstan-baseline.neon
- psalm-baseline.xml
Fixes https://github.com/inblockio/DataAccounting/issues/146
> Export page improvements

- includes/Hasher/RevisionVerificationBuilder.php
> [BREAKING][BUGFIX] Properly use domain manifest verification hash for witness hash

- extension.json
- includes/API/GetServerInfoHandler.php
- includes/API/WriteStoreSignedTxHandler.php
- includes/Config/DataAccounting.php
- includes/Config/DataAccountingConfig.php
- includes/Config/Handler.php
- includes/Config/ServiceWiring.php
- includes/ExportImport/ServiceWiring.php
- includes/Hooks.php
- includes/SpecialDataAccountingConfig.php
- includes/SpecialVerifiedExport.php
- includes/SpecialVerifiedImport.php
- includes/SpecialWitness.php
- includes/SpecialWitnessPublisher.php
- includes/Util.php
- sql/data_accounting.sql
issue: https://github.com/inblockio/DataAccounting/issues/176
> Add database config storage for all 'da' configs

- includes/API/GetServerInfoHandler.php
- includes/API/WriteStoreSignedTxHandler.php
- includes/API/WriteStoreWitnessTxHandler.php
- includes/ApiUtil.php
- includes/Config/DataAccountingConfig.php
- includes/Util.php
- psalm-baseline.xml
- psalm.xml
> chore: 🤖 Add some typing

- extension.json
- includes/API/ContextAuthorized.php
- includes/API/GetPageAllRevsHandler.php
- includes/API/GetPageByRevIdHandler.php
- includes/API/GetPageLastRevHandler.php
- includes/API/GetServerInfoHandler.php
- includes/API/GetWitnessDataHandler.php
- includes/API/RequestHashHandler.php
- includes/API/RequestMerkleProofHandler.php
- includes/API/VerifyPageHandler.php
- tests/phpunit/integration/DAApiTest.php
- tests/phpunit/integration/WitnessTest.php
https://github.com/inblockio/DataAccounting/issues/187
> Add context authorized rest api feature

- includes/SpecialDataAccountingConfig.php
- includes/SpecialVerifiedExport.php
- includes/SpecialVerifiedImport.php
- includes/SpecialWitness.php
- includes/SpecialWitnessPublisher.php
- tests/phpunit/integration/WitnessTest.php
https://github.com/inblockio/DataAccounting/issues/150
> Add annotations to special pages

- includes/DAAction.php
https://github.com/inblockio/DataAccounting/issues/150
> Add annotations to DAAction

- includes/API/WriteStoreSignedTxHandler.php
- includes/API/WriteStoreWitnessTxHandler.php
- includes/HashWriterHooks.php
- includes/SpecialWitness.php
- includes/SpecialWitnessPublisher.php
- includes/VerifiedWikiImporter.php
- modules/publishDomainManifest/index.js
- psalm-baseline.xml
- tests/phpunit/integration/WitnessTest.php
> Mainnet over testnet

- composer.json
- extension.json
- includes/API/GetHashChainInfoHandler.php
- includes/Override/Storage/DAPageUpdater.php
- includes/SpecialWitness.php
- includes/SpecialWitnessPublisher.php
- tests/phpunit/unit/HashingServiceTest.php
https://github.com/inblockio/DataAccounting/issues/154
> Replace Api.php and Util.php in special witness and witnessPublisher

- includes/SpecialVerifiedImport.php
- includes/VerifiedWikiImporter.php
- phpstan-baseline.neon
https://github.com/inblockio/DataAccounting/issues/264
> Fix: Add missing use statement for NamespaceImportTitleFactory

- README.md
Some cosmetic updates and spelling fixes.
We need to address the TODO parts in the text.
> Small updates to DataAccounting README.md

- extension.json
- includes/API/GetHashChainInfoHandler.php
- includes/API/GetPageLastRevHandler.php
- includes/API/TransclusionHashUpdater.php
- modules/ext.DataAccounting.signMessage/index.js
- modules/ext.dataAccounting.updateTransclusionHashes.js
- tests/phpunit/integration/DAApiTest.php
We need to do this because sometimes the page title contains slash.
> Change title in API endpoints to URL param

- .github/workflows/ci.yml
- .github/workflows/installWiki.sh
https://github.com/inblockio/DataAccounting/issues/244
> Add manual patch for setProvides signature in Composer

- includes/SpecialWitness.php
- includes/Verification/WitnessLookup.php
- sql/data_accounting.sql
- sql/migrations/0013_revamp_witness_merkle_tree.sql
- sql/migrations/0014_fix_merkle_tree_depth_type.sql
> Prevent duplicate Merkle tree insertion

- includes/Verification/VerificationEngine.php
https://github.com/inblockio/mediawiki-extensions-Aqua/issues/292
> Skip content verification injection when config is disabled

- i18n/de.json
- i18n/en.json
- includes/Content/TransclusionHashes.php
- includes/TransclusionManager.php
- includes/Util/TransclusionHashExtractor.php
Fixes https://github.com/inblockio/mediawiki-extensions-Aqua/issues/307
> fix: Do not fatal when verificaiton data for transclusion does not exist

- includes/SpecialWitness.php
> style: Make Domain Snapshot Generator button nicer

- includes/Config/Handler.php
- includes/RevisionXmlBuilder.php
- includes/Verification/VerificationEntityFactory.php
- includes/Verification/VerificationLookup.php
- includes/Verification/WitnessLookup.php
- sql/data_accounting.sql
https://github.com/inblockio/mediawiki-extensions-Aqua/issues/311
> Avoid * select and add type casting for results

- .github/workflows/ci.yml
- tests/phpunit/Integration/API/GetRevisionHandlerTest.php
- tests/phpunit/Integration/API/GetRevisionHashesHandlerTest.php
- tests/phpunit/Integration/API/HashChainInfoHandlerTest.php
- tests/phpunit/Integration/API/TransclusionHashUpdaterTest.php
https://github.com/inblockio/mediawiki-extensions-Aqua/issues/326
> Tests: Fix broken api tests

- includes/Transfer/Importer.php
- includes/Transfer/TransferEntityFactory.php
- includes/Verification/VerificationEngine.php
Solving https://github.com/inblockio/mediawiki-extensions-Aqua/issues/361
@it-spiderman please review & merge after testing
> Patching null signature

- modules/ext.DataAccounting.signMessage/index.js
> Use recovered wallet address as payload for storing signature request

- extension.json
- includes/AuthGuardianProvider.php
- includes/maintenance/createSysopUser.php
Grant access for guardian user on REST
Create sysop user script
ERM37139
> Unauthenticated access guardian

- docs/api.yaml
- extension.json
- includes/API/GetBranchHandler.php
This is a draft to solve https://github.com/inblockio/mediawiki-extensions-Aqua/issues/375 according to our needs.
> Draft for get_branch

- docs/api.yaml
- includes/API/RecentChangesHandler.php
- includes/Hook/Update.php
- includes/RevisionManipulator.php
- includes/Verification/VerificationLookup.php
- sql/revision_verification_archive.sql
https://github.com/inblockio/mediawiki-extensions-Aqua/issues/383
**This change adds a database table! This means that on existing PKCs, running maintenance/update.php is required!**
> Include deleted revision in recent_changes

- includes/SpecialInbox.php
> #408: Fix disregard draft

- includes/Transfer/Importer.php
> #411: Fix file upload fails

- docs/api.yaml
- extension.json
- includes/API/DeleteRevisionByHashHandler.php
- includes/RevisionManipulator.php
- includes/ServiceWiring.php
- tests/phpunit/Unit/RevisionManipulatorTest.php
If non-latest revision is given, will delete all newer revisions starting at given hash. If first revision is given, the whole page is deleted
> Delete revision by hash
